### ISSUE TITLE
Setup continuous integration?

### ISSUE THREAD

**Issue by tomlepaine** [aiUIUC/pyAIUtils#13]
Hi @arunmallya @kevjshih @BigRedT,
It sounds like there is interest in **continuous integration** for this repo. And since we have a few tests, it seems like a good idea.

Someone suggested [Travis CI](https://travis-ci.org/). It seems like all you need to get travis ci working is:
- Give travis ci access to your repo.
- Make a config file called `.travis.yml` that says: which version of python to try, which dependencies need to be installed, and what testing package to use.
- Save the `.travis.yml` in your repo.

[Blocks](https://github.com/mila-udem/blocks) is a neural network library that used a lot of the python scientific computing stack and they use travis ci too! We can probably copy a lot of what they do. Here is their `.travis.yml` file: [link](https://github.com/mila-udem/blocks/blob/master/.travis.yml)

Who wants to try doing this? :smiling_imp:

**Comment by arunmallya** [comment]
Ahem ahem, How -> Who.

**Comment by arunmallya** [comment]
I'm up for doing it, probably over the weekend.

**Comment by tomlepaine** [comment]
Great. Assigning you now.

**Comment by tomlepaine** [comment]
Also extra credit: There is something called [coveralls](https://github.com/z4r/python-coveralls) which can check out test coverage.

**Comment by danyaljj** [comment]
Just a side note: in our experience [Semaphore](semaphoreci.com) was much more stable/reliable that travis (at least for our jdk-based codes). The downside is that you get only 100 free runs for each month (per project).

**Comment by tomlepaine** [comment]
@danyaljj if debugging this install takes much longer maybe we should switch. Anyone have any examples of setting up tensorflow with Semaphore?

In the mean time I am trying to trouble shoot using a local docker image as described on the [travis-ci docs](https://docs.travis-ci.com/user/common-build-problems/#Troubleshooting-Locally-in-a-Docker-Image).

**Comment by tomlepaine** [comment]
Thanks guys. Looks like we got continuous integrations working now :tada: so I am closing this.
