### ISSUE TITLE
random_normal_initializer is wrong for both conv and dense

### ISSUE THREAD

**Issue by mbz** [aiUIUC/pyAIUtils#25]
In the `layers.py` we are initializing the weights by the following line:

```w_init = tf.random_normal_initializer(stddev)```

but the first argument should be mean (which is 0.0 in this case). so it should be updated to:

```w_init = tf.random_normal_initializer(0.0, stddev)```

I would do this myself, if I had write permission! :)

**Comment by tomlepaine** [comment]
Oh man. My bad. I gave you permission, please fix.

**Comment by mbz** [comment]
It seems that I still do not have write permission.

```remote: Permission to aiUIUC/pyAIUtils.git denied to mbz.
fatal: unable to access 'https://github.com/aiUIUC/pyAIUtils/': The requested URL returned error: 403```
